### ISSUE TITLE
Screen shakes in Chrome when messaging

### ISSUE THREAD

**Issue by direclown** [pupbrained/calckey-nix#1]
## 💡 Summary

In Google Chrome, when messaging in calckey (specifically the instance calckey.social), sometimes the screen will "shake" or "vibrate" while chatting with someone.

## 🥰 Expected Behavior

Ideally, when chatting, the site/text would stay stationary and not move while typing.

## 📝 Steps to Reproduce

1. Log onto calckey.social in Chrome.
2. Start a "new chat" on the chat feature.
3. Talk to the person for a minute or so. At some point, the entire screen will start shaking up and down or "vibrating" (this is the best way I can explain it!). If I reset the page, it stops. But sometimes it will occur again after a few minutes. 
4. I have not yet tried this out on Linux at home; I may test it there and see if the same thing happens on different OS's or browsers, or if it is just in Chrome on Windows. 

## 📌 Environment

Misskey version: Calckey v14.0.0-dev13
Your OS: Windows 11
Your browser: Google Chrome

**Comment by ThatOneCalculator** [comment]
You're looking for https://calckey.org/calckey/calckey

**Comment by direclown** [comment]
Oh, thank you
